---
hdp_main_repo_url: "{{ base_url }}/HDP/centos{{ ansible_distribution_major_version }}/{{ hdp_major_version }}.x/updates/{{ hdp_version }}"
hdf_main_repo_url: "{{ base_url }}/HDF/centos{{ ansible_distribution_major_version }}/{{ hdf_major_version }}.x/updates/{{ hdf_version }}"
main_os_target: "operating_systems/redhat{{ ansible_distribution_major_version }}"

utils_repo_url: "{{ base_url }}/HDP-UTILS-{{ utils_version }}/repos/centos{{ ansible_distribution_major_version }}"
utils_os_target: "operating_systems/redhat{{ ansible_distribution_major_version }}/repositories/HDP-UTILS-{{ utils_version }}"
