---
hdp_main_repo_url: "{{ base_url }}/HDP/suse11sp3/{{ hdp_major_version }}.x/updates/{{ hdp_version }}"
hdf_main_repo_url: "{{ base_url }}/HDF/suse11sp3/{{ hdf_major_version }}.x/updates/{{ hdf_version }}"
main_os_target: "operating_systems/suse{{ ansible_distribution_major_version }}"

utils_repo_url: "{{ base_url }}/HDP-UTILS-{{ utils_version }}/repos/suse11sp3"
utils_os_target: "operating_systems/suse{{ ansible_distribution_major_version }}/repositories/HDP-UTILS-{{ utils_version }}"
