---
postgres_port: 5432
mysql_port: 3306

#################################
## dynamic blueprint variables ##
#################################
registry_dns_bind_port: '53'

## ZK  zoo.cfg:
zookeeper_dataDir: "/hadoop/zookeeper"

## HDFS
dfs_namenode_checkpoint_dir: "/hadoop/hdfs/namesecondary"
dfs_namenode_name_dir: "/hadoop/hdfs/namenode"
dfs_datanode_data_dir: "/hadoop/hdfs/data"
dfs_journalnode_edits_dir: "/hadoop/hdfs/journalnode"
#nfs_file_dump_dir: "/tmp/.hdfs-nfs"
hdfs_datanode_failed_volumes_tolerated: 0
hdfs_replication: 3

hdfs_dtnode_heapsize: "1024m"
hdfs_namenode_heapsize: "2048m"
hdfs_namenode_opt_maxnewsize: "384m"
hdfs_namenode_opt_newsize : "384m"

## Yarn
yarn_nodemanager_local_dirs: "/hadoop/yarn/local"
yarn_nodemanager_log_dirs: "/hadoop/yarn/log"
yarn_timeline_service_leveldb_state_store_path: "/hadoop/yarn/timeline"
yarn_timeline_service_leveldb_timeline_store_path: "/hadoop/yarn/timeline"

## Kafka
kafka_default_replication_factor: 1
kafka_log_dirs: "/kafka-logs"
kafka_log_retention_bytes: "-1"
kafka_log_retention_hours: "168"
kafka_num_partitions: 1
kafka_offsets_topic_replication_factor: 3

# Oozie
oozie_data_dir: "/hadoop/oozie/data"

## NIFI
nifi_initial_mem: "512m"
nifi_max_mem: "512m"
nifi_content_repository_dir_default: "/var/lib/nifi/content_repository"
nifi_database_dir: "/var/lib/nifi/database_repository"
nifi_flowfile_repository_dir: "/var/lib/nifi/flowfile_repository"
nifi_provenance_repository_dir_default: "/var/lib/nifi/provenance_repository"
nifi_internal_dir: "/var/lib/nifi"
nifi_state_dir: "{nifi_internal_dir}/state/local"
nifi_flow_config_dir: "{nifi_internal_dir}/conf"
#nifi_config_dir: "{nifi_install_dir}/conf"
#Note: left out (in 1.try) because it uses ansible/jinja2 templating
#nifi_database_directory: "{{nifi_database_dir}}"

## NIFI-Registry
nifi_registry_initial_mem: "512m"
nifi_registry_max_mem: "512m"
nifi_registry_internal_dir: "/var/lib/nifi-registry"
nifi_registry_database_dir: "{nifi_registry_internal_dir}/database"
nifi_registry_internal_config_dir: "{nifi_registry_internal_dir}/conf"
