---
- name: Load variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution|lower }}.yml"
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family|lower }}.yml"
        - defaults.yml
      paths:
        - ../database/vars

- name: Fail if trying to install MariaDB on unsupported OS
  fail:
    msg: "MariaDB is not available or supported on SLES 11 and Debian/Ubuntu"
  when: database == "mariadb" and ((ansible_os_family|lower == "suse" and ansible_distribution_major_version|int == 11) or ansible_os_family|lower == "debian")

- block:
    - name: Add the mysql repository (yum)
      yum_repository:
        name: mysql-community
        description: "MySQL {{ mysql_version }} Community Server"
        baseurl: "{{ mysql_repo_url }}"
        state: present
        gpgcheck: yes
        gpgkey: "{{ mysql_repo_key }}"
      when: ansible_os_family|lower == "redhat"

    - name: Add the mysql repository (zypper)
      zypper_repository:
        name: mysql-community
        description: "MySQL {{ mysql_version }} Community Server"
        repo: "{{ mysql_repo_url }}"
        state: present
        disable_gpg_check : yes
        runrefresh: yes
      when: ansible_os_family|lower == "suse"

    - name: Add the mysql repository key (apt)
      apt_key:
        data: "{{ lookup('file', mysql_repo_keyfile) }}"
        id: "{{ mysql_repo_key }}"
      when: ansible_os_family|lower == "debian"

    - name: Add the mysql repository (apt)
      apt_repository:
        filename: mysql
        repo: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - "deb {{ mysql_repo_url }} {{ ansible_lsb.codename }} mysql-apt-config"
        - "deb {{ mysql_repo_url }} {{ ansible_lsb.codename }} mysql-{{ mysql_version }}"
        - "deb {{ mysql_repo_url }} {{ ansible_lsb.codename }} mysql-tools"
        - "deb-src {{ mysql_repo_url }} {{ ansible_lsb.codename }} mysql-{{ mysql_version }}"
      when: ansible_os_family|lower == "debian"
  when: database == "mysql"

- block:
    - name: Add the mariadb repository (yum)
      yum_repository:
        name: mariadb
        description: "MariaDB"
        baseurl: "{{ mariadb_repo_url }}"
        state: present
        gpgcheck: yes
        gpgkey: "{{ mariadb_repo_key }}"
      when: ansible_os_family|lower == "redhat"

    - name: Add the mariadb repository (zypper)
      zypper_repository:
        name: mariadb
        description: "MariaDB"
        repo: "{{ mariadb_repo_url }}"
        state: present
        disable_gpg_check : yes
        runrefresh: yes
      when: ansible_os_family|lower == "suse"
  when: database == "mariadb"

- name: Install {{ database }} database packages
  package:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items: "{{ hostvars[inventory_hostname][database + '_packages'] | join(',') }}"

- block:
    - name: Initiate postgres
      become: yes
      shell: "{{ postgres_initdb_command }}"
      args:
        creates: "{{ postgres_hba_file }}"
        warn: false

    - name: Configure postgres to listen on all interfaces
      lineinfile:
        path: "{{ postgres_config_file }}"
        line: "listen_addresses = '*'"
        regexp: '^#?listen_addresses\s+='
        state: present
      notify: Restart postgres
  when: database == "postgres"

- block:
    - name: Configure {{ database }} to listen on all interfaces
      ini_file:
        path: "{{ (database == 'mariadb') | ternary(mariadb_config_file, mysql_config_file) }}"
        create: no
        section: "mysqld"
        option: "bind-address"
        value: "*"
        no_extra_spaces: yes
        state: present
      notify: Restart {{ database }}
  when: database == "mysql" or database == "mariadb"

- meta: flush_handlers

- name: Make sure the {{ database }} service is started
  service:
    name: "{{ hostvars[inventory_hostname][database + '_service_name'] }}"
    state: started

- name: Make sure the {{ database }} service is enabled
  service:
    name: "{{ hostvars[inventory_hostname][database + '_service_name'] }}"
    enabled: yes
  ignore_errors: true

- name: Prepare the ambari database
  include_tasks: "{{ database | regex_replace('mariadb', 'mysql') }}_play.yml"
  vars:
    db_name: "{{ database_options.ambari_db_name }}"
    db_username: "{{ database_options.ambari_db_username }}"
    db_password: "{{ database_options.ambari_db_password }}"
    db_client_hosts: "{{ inventory_hostname }}"

- name: Prepare the hive database
  include_tasks: "{{ database | regex_replace('mariadb', 'mysql') }}_play.yml"
  vars:
    db_name: "{{ database_options.hive_db_name }}"
    db_username: "{{ database_options.hive_db_username }}"
    db_password: "{{ database_options.hive_db_password }}"
    db_client_hosts: "{{ hiveserver_hosts }}"
  when: hiveserver_hosts is defined and hiveserver_hosts|length > 0

- name: Prepare the oozie database
  include_tasks: "{{ database | regex_replace('mariadb', 'mysql') }}_play.yml"
  vars:
    db_name: "{{ database_options.oozie_db_name }}"
    db_username: "{{ database_options.oozie_db_username }}"
    db_password: "{{ database_options.oozie_db_password }}"
    db_client_hosts: "{{ oozie_hosts }}"
  when: oozie_hosts is defined and oozie_hosts|length > 0

- name: Prepare the ranger database
  include_tasks: "{{ database | regex_replace('mariadb', 'mysql') }}_play.yml"
  vars:
    db_name: "{{ database_options.rangeradmin_db_name }}"
    db_username: "{{ database_options.rangeradmin_db_username }}"
    db_password: "{{ database_options.rangeradmin_db_password }}"
    db_client_hosts: "{{ rangeradmin_hosts }}"
  when: rangeradmin_hosts is defined and rangeradmin_hosts|length > 0

- name: Prepare the registry database
  include_tasks: "{{ database | regex_replace('mariadb', 'mysql') }}_play.yml"
  vars:
    db_name: "{{ database_options.registry_db_name }}"
    db_username: "{{ database_options.registry_db_username }}"
    db_password: "{{ database_options.registry_db_password }}"
    db_client_hosts: "{{ registry_hosts }}"
  when: registry_hosts is defined and registry_hosts|length > 0

- name: Prepare the streamline database
  include_tasks: "{{ database | regex_replace('mariadb', 'mysql') }}_play.yml"
  vars:
    db_name: "{{ database_options.streamline_db_name }}"
    db_username: "{{ database_options.streamline_db_username }}"
    db_password: "{{ database_options.streamline_db_password }}"
    db_client_hosts: "{{ streamline_hosts }}"
  when: streamline_hosts is defined and streamline_hosts|length > 0
