---
packages:
  - openssh                 # scp required by Ambari
  - curl                    # curl required by Ambari
  - php5-curl               # php-curl requred by Ambari in SLES
  - unzip                   # unzip required by Ambari
  - tar                     # tar required by Ambari
  - wget                    # wget required by Ambari
  - openssl                 # openssl required by Ambari
  - ntp                     # ntp required by Hadoop
  - libopenssl-devel        # openssl-devel recommended for Ranger KMS
  - libtirpc-devel          # libtirpc required by HDP 2.6+

openjdk_package: java-1_8_0-openjdk-devel

ntp_service_name: ntpd

firewall_service_name: SuSEfirewall2

update_grub_command: 'grub2-mkconfig -o /boot/grub2/grub.cfg'
